project proposal added
BU-Spark/CS506-Spring2020-Projects pull request #10
Opened 2020-02-10 22:35 UTC by FuqingWang

## Description of Change

Description goes here

## Team Name and Contributers

Team name and list of contributers for this PR goes here.

## Checklist

Before creating your PR, please ensure the following requirements.

### General

- [ ] PR does **not** include irrelevant or hidden files (i.e. `__pycache__`, `.vscode`... etc.)
- [ ] Changes are in the correct folder
- [ ] There are no merge conflicts
- [ ] Commit messages are sensible and descriptive

### Code

- [ ] Implementation matches proposed design
- [ ] Documentation on how to run the code is created/updated
- [ ] Code is legible

### Report

- [ ] Report meets the deliverable criteria
- [ ] Proposal is up to date with latest decisions

2020-02-12 16:22 UTC, gallettilance requested changes
@FuqingWang You need to add this to a folder named after the name of your project.

2020-02-12 22:01 UTC, rishabnayak requested changes
Hey guys, just took a look at your project proposal. I feel like it needs some more information on how you plan to achieve your goals. What we're looking for is a project plan stating how you want to use the tools and the datasets that are at your disposal to achieve your goals in a reasonable timeframe. 

Stay tuned for an email from me so that we can setup a time to meet and try to figure out how we want to move ahead from here.

2020-02-19 01:51 UTC, gallettilance requested changes
@FuqingWang Please squash your commits so that there is only 1 commit in this PR.

2020-02-20 17:56 UTC, gallettilance approved these changes

2020-02-20 17:56 UTC, merged