Haverhill JuntaoWang Deliverable 0
BU-Spark/CS506-Spring2020-Projects pull request #3
Opened 2020-02-09 20:17 UTC by DaoDaoNoCode

## Description of Change

Add Deliverable 0 file.

## Team Name and Contributers

Juntao Wang, Yifei Fang, Yanshan Song, Tian Ding

## Checklist

Before creating your PR, please ensure the following requirements.

### General

- [ ✅] PR does **not** include irrelevant or hidden files (i.e. `__pycache__`, `.vscode`... etc.)
- [ ✅] Changes are in the correct folder
- [ ✅] There are no merge conflicts
- [ ✅] Commit messages are sensible and descriptive

### Code

- [ ] Implementation matches proposed design
- [ ] Documentation on how to run the code is created/updated
- [ ] Code is legible

### Report

- [ ✅] Report meets the deliverable criteria
- [ ✅] Proposal is up to date with latest decisions

2020-02-12 22:22 UTC, rishabnayak requested changes
Hey guys, just took a look at your project proposal. I feel like it needs some more information on how you plan to achieve your goals. What we're looking for is a project plan stating how you want to use the tools and the datasets that are at your disposal to achieve your goals in a reasonable timeframe.

Stay tuned for an email from me so that we can setup a time meet and try to figure out how we want to move ahead from here.

2020-02-16 16:14 UTC, gallettilance commented
@DaoDaoNoCode Please address feedback asap

2020-02-18 01:08 UTC, rishabnayak approved these changes

2020-02-18 01:09 UTC, rishabnayak commented
LGTM, please sign up for a time to meet via the link sent to you via email. I'm merging the PR right away.

2020-02-18 01:09 UTC, merged